name: Ruby

on:
  push:
    branches:
      - deploy

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.0.3'

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: false
    - name: Run the bundle install
      run: bundle install
    - name: Run rubocop on changed files
      run: |
        URL="https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files"
        FILES=$(curl -s -X GET -G $URL | jq -r '.[] | .filename')
        if echo $FILES | grep -q ".rb"; then
          echo "rb file changed!!"
          echo $FILES
          rubocop --color $FILES
        else
          echo "no rb files changed!!"
        fi
    # - name: Run rubocop on changed files
    #   run: ./bin/rubocop_pr_offenses
    - name: Run rspec
      run: bundle exec rspec
    # - name: Run the default task
    #   run: bundle exec rake
    - name: Run the rspec-openapi task
      run: OPENAPI=1 bundle exec rspec spec/ engines/perk/spec
    - name: Run the combine-openapi task
      run: ./bin/combine_openapi
