name: Ruby

on:
  push:
    branches:
      - deploy

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.0.3'

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: false
    - name: Run the bundle install
      run: bundle install
    - name: Run rubocop on changed files
      run: |
        echo "starting script"
        URL="https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files"
        FILE_PATTERN="(\.r[bu]$|/bundle$|/setup$|/rails$|/rake$|/?Gemfile$|/?Rakefile$|\.gemspec$|\.rake$)"
        FILES=""
        FILE_SET="START"
        PAGE=1
        while [ ! -z "$FILE_SET" ]
        do
          URL_WITH_PAGE="$URL?page=$PAGE"
          FILE_SET=$(curl -s -X GET -G $URL_WITH_PAGE | jq -r '.[] | .filename' | tr '\n' ' ')
          if [ ! -z "$FILES" ]; then
            FILES="$FILES $FILE_SET"
          else
            FILES="$FILE_SET"
          fi
          PAGE=`expr $PAGE + 1`
        done
        FILTERED_FILES=$(echo $FILES | tr ' ' '\n' | egrep -i "$FILE_PATTERN" || true)
        if [ ! -z "$FILTERED_FILES" ]; then
          echo "rb file changed!!"
          echo $FILTERED_FILES | xargs rubocop --color --force-exclusion
        else
          echo "no rb files changed!!"
        fi
      if: github.event_name == 'pull_request'
    - name: Run rspec
      run: bundle exec rspec
    - name: Run the rspec-openapi task
      run: OPENAPI=1 bundle exec rspec spec/ engines/perk/spec
    - name: Run the combine-openapi task
      run: ./bin/combine_openapi
